<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'DartComm\Exception\ConnectionFailed'            => __DIR__ . '/lib/DartComm/Exception/ConnectionFailed.php',
    'DartComm\Iterator\Models'                       => __DIR__ . '/lib/DartComm/Iterator/Models.php',
    'DartComm\Model\ModelAbstract'                   => __DIR__ . '/lib/DartComm/Model/ModelAbstract.php',
    'DartComm\Model\Message'                         => __DIR__ . '/lib/DartComm/Model/Message.php',
    'DartComm\Model\Mailbox'                         => __DIR__ . '/lib/DartComm/Model/Mailbox.php',
    'DartComm\Model\Contact'                         => __DIR__ . '/lib/DartComm/Model/Contact.php',
    'DartComm\Model\Identity'                        => __DIR__ . '/lib/DartComm/Model/Identity.php',
    'DartComm\Comm\Protocol\ProtocolInterface'       => __DIR__ . '/lib/DartComm/Comm/Protocol/ProtocolInterface.php',
    'DartComm\Comm\Protocol\Imap'                    => __DIR__ . '/lib/DartComm/Comm/Protocol/Imap.php',
    'ApplicationTest\Bootstrap'                      => __DIR__ . '/test/Bootstrap.php',
    'ApplicationTest\Controller\IndexControllerTest' => __DIR__ . '/test/ApplicationTest/Controller/IndexControllerTest.php',
    'Application\Module'                             => __DIR__ . '/Module.php',
    'Application\Controller\IndexController'         => __DIR__ . '/src/Application/Controller/IndexController.php',
);
